version: '3'
services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r5t6y
      MYSQL_DATABASE: social_network
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    volumes:
      - ./src/main/resources/static/tables.ddl:/data/init.sql
    command: --init-file /data/init.sql
    ports:
      - "3306:3306"
  application:
    image: highloadsn:latest
    restart: always
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/social_network?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"